---
- hosts: ip-172-32-135-73
  remote_user: root
  roles:
    - role: orderers

- hosts: ip-172-32-140-114
  remote_user: root
  roles:
    - role: peers
    - role: channels_create
    - role: channels_join
    - role: chaincodes_install
    - role: chaincodes_instantiate

- hosts: ip-172-32-244-154
  remote_user: root
  roles:
    - role: peers
    - role: channels_create
    - role: channels_join
    - role: chaincodes_install
    - role: chaincodes_instantiate
