- name: "create cas"
  include_role:
    name: dlt_component
  vars:
    component_name: "{{ item.key }}"
    component_config: "{{ item.value['config'] }}"
    platform: "hyperledger-fabric"
    type: "cas"
  loop: "{{ dlt['hyperledger-fabric']['cas'] | default({}) | dict2items }}"
