- name: "instantiate chaincode {{ chaincode_name }}"
  include_role:
    name: dlt_component
  vars:
    component_name: "instantiate-{{ chaincode_name }}-{{ chaincodechannel['name'] }}"
    component_config: "{{ chaincode['config'] }}"
    platform: "hyperledger-fabric"
    type: "instantiate_chaincode_job"
  loop: "{{ chaincode['config']['channels'] }}"
  when: "chaincodechannel['instantiator'] is defined"
  loop_control: 
    loop_var: chaincodechannel

  