---
- name: Ensures {{ values_dir }} dir exists
  file:
    path: "{{ values_dir }}"
    recurse: yes
    state: directory
  
- name: "create values file for {{ component_name }}"
  template:
    src: "{{ dlt_templates[type] | default('dlt_component.tpl') }}"
    dest: "{{ values_file }}"
  vars:
    values_file: "{{ values_dir }}/{{ component_name }}.yaml"
    config: "{{ component_config }}"
    othercomponents: "{{ dlt }}"

- name: "helm release {{ component_name }}"
  command: "{{ helm_cmd }} upgrade --install {{ component_name }} {{ charts[type]['chart_name'] }} --namespace {{ namespace }} --version {{ charts[type]['version'] }} --values {{ values_dir }}/{{ component_name }}.yaml --home {{ helm_home }}"

